import { createContext, useContext, useState } from 'react'

const T = {
  en: {
    // ── Utility bar ───────────────────────────────────────────────────────────
    announce: 'Complimentary engraving · Free shipping over 1 500 kr · Crafted in Stockholm',

    // ── Nav ───────────────────────────────────────────────────────────────────
    women: 'Women', men: 'Men', silverStone: 'Silver & Stone',
    sets: 'Sets', heritage: 'Heritage', collection: 'Collection',
    shopHer: 'Shop her', shopHim: 'Shop him',
    necklaces: 'Necklaces', earrings: 'Earrings', rings: 'Rings', bracelets: 'Bracelets',
    signetRings: 'Signet rings', chains: 'Chains', cufflinks: 'Cufflinks', viewAll: 'View all →',

    // ── Home ──────────────────────────────────────────────────────────────────
    heroEyebrow: 'The Línea Collection', heroH1a: 'In full', heroH1b: 'bloom',
    shopCollection: 'Shop the collection', ourStory: 'Our story',
    findYourPiece: 'Find your piece', shopByCategory: 'Shop by category',
    newArrivals: 'New arrivals', featuredPieces: 'Featured pieces',
    viewAll2: 'View all', addToCart: 'Add to cart',
    marquee: 'Recycled solid gold ✦ Crafted in Stockholm ✦ Ancient Swedish craft ✦ Lifetime repair',
    forHer: 'For her', forHim: 'For him', forAll: 'For all',
    newIn: 'New in', lowStock: 'Low stock',

    // ── Shop ──────────────────────────────────────────────────────────────────
    all: 'All',
    silverStoneEyebrow: 'Natural stone, hand-set in sterling silver',
    shopEmpty: 'No pieces match this filter yet.',

    // ── Cart ──────────────────────────────────────────────────────────────────
    yourCart: 'Your cart', cartEmpty: 'Your bag is empty',
    cartEmptySub: 'Pieces you add will appear here.',
    subtotal: 'Subtotal', toCheckout: 'Go to checkout',
    freeShippingNote: 'Free shipping over 1 500 kr',
    continueShopping: 'Continue shopping',

    // ── Product page ──────────────────────────────────────────────────────────
    addToCartBtn: 'Add to cart',
    back: '← Back',
    personalisableFlag: '✦ This piece can be personalised',
    metalLabel: 'Metal',
    metalGold: 'Gold', metalWhiteGold: 'White gold', metalSilver: 'Silver',
    accordionDetails: 'Details & materials',
    accordionSizing: 'Sizing & fit',
    accordionShipping: 'Shipping & returns',
    persEyebrow: 'Made for you',
    persH2: 'Design your own',
    persIntro: 'Choose your initials, symbol, stone, and metal. We engrave each piece by hand before it ships.',

    // ── Personalisation panel ─────────────────────────────────────────────────
    persPreviewNote: 'Live preview · not to scale',
    persHeadline: 'Personalise this piece',
    persInitialsLabel: 'Engraved initials',
    persInitialsPlaceholder: 'e.g. L · LA · LIA',
    persInitialsHint: '1–3 letters, spaced with · if needed',
    persSymbolLabel: 'Engraved symbol',
    persSymbol1: 'Sun cross', persSymbol2: 'Eternity knot', persSymbol3: 'Elk flower',
    persMetal: 'Metal',
    persMetalSilver: 'Sterling silver', persMetalGold: 'Solid gold',
    persStoneLabel: 'Stone accent', persStoneNote: '— choose for meaning',
    persStoneNone: 'No stone', persStoneGarnet: 'Garnet', persStoneMoonstone: 'Moonstone',
    persStoneAmethyst: 'Amethyst', persStoneOnyx: 'Black onyx',
    persChainLabel: 'Chain length',
    persAddInitials: 'ADD INITIALS',
    persDisclaimer: 'Each piece is hand-finished to order · allow 5–7 days',

    // ── Checkout ──────────────────────────────────────────────────────────────
    placeOrder: 'Place order',
    orderSummary: 'Order summary',
    shipping: 'Shipping', free: 'Free', total: 'Total',
    firstName: 'First name', lastName: 'Last name',
    address: 'Address', city: 'City', postalCode: 'Postal code', country: 'Country',
    email: 'Email', phone: 'Phone',
    cardNumber: 'Card number', expiry: 'Expiry', cvc: 'CVC',

    // ── About page ────────────────────────────────────────────────────────────
    aboutEyebrow: 'Since 2026',
    aboutH1: 'Old craft. New hands.',
    aboutQuote: '"Swedish silversmiths once engraved motifs that carried meaning for generations. I wanted to bring that back — not as nostalgia, but as something you actually wear."',
    aboutP1: 'Founded by Liana in Stockholm, LIANELA revives pre-industrial Swedish metalsmithing — drawing on Norse knotwork, folk motifs, and ancient soldering techniques that largely disappeared with mass production. Each piece is made in small batches from recycled solid gold and responsibly sourced stones.',
    aboutP2: 'We believe jewelry should be lived in — worn daily, passed down, repaired rather than replaced. Every LIANELA order carries a lifetime craftsmanship promise.',
    aboutStat1: 'Recycled gold', aboutStat2: 'Repair promise', aboutStat3: 'Stockholm dispatch',
    exploreCollection: 'Explore the collection',

    // ── Heritage page ─────────────────────────────────────────────────────────
    heritageEyebrow: 'Swedish craft heritage',
    heritageH1: 'Symbols carried in silver',
    heritageP: 'Every motif we engrave traces back to ancient Swedish metalsmithing — patterns cut by hand into iron, bone, and silver for over a thousand years. We carry them forward in sterling silver, chosen for what they mean, not just how they look.',
    heritageCtaP: 'Want a symbol that isn\'t shown here, sized or engraved for someone specific?',
    heritageCtaBtn: 'Request a custom piece',

    // ── Custom order page ─────────────────────────────────────────────────────
    customTitle: 'Custom Order',
    customEyebrow: 'Made only for you',
    customH1: 'Design your own piece',
    customHeroDesc: 'Choose your piece and stone. Add a name, an initial, a date. We engrave and hand-finish every custom order in recycled sterling silver.',
    customBegin: 'Begin',
    stepPiece: 'Piece', stepStone: 'Stone', stepEngrave: 'Engrave', stepContact: 'Contact',
    customPieceQ: 'What would you like to create?',
    customPieceDesc: 'Ring or bracelet — we\'ll craft the rest around your choice.',
    pieceRing: 'Ring', pieceRingSub: 'Band / signet',
    pieceBracelet: 'Bracelet', pieceBraceletSub: 'Cuff / bangle',
    pieceEngRing: 'Engraved on the inner band — a secret message only you know.',
    pieceEngBracelet: 'Engraved on the outer face — visible, personal, and permanent.',
    backToSite: '← Back to site',
    nextStone: 'Next — Stone',
    customStoneQ: 'Choose your stone',
    customStoneDesc: 'Each stone carries its own meaning. All pieces are crafted in recycled sterling silver.',
    silverBadge: 'Recycled Sterling Silver · 925',
    silverBadgeNote: 'ethically sourced · hand-polished · hallmarked',
    stoneNone: 'No stone', stoneGarnet: 'Garnet', stoneMoonstone: 'Moonstone',
    stoneAmethyst: 'Amethyst', stoneOnyx: 'Black onyx', stoneTurquoise: 'Turquoise',
    stoneMeanGarnet: 'Courage & vitality', stoneMeanMoonstone: 'Balance & new beginnings',
    stoneMeanAmethyst: 'Peace & intuition', stoneMeanOnyx: 'Strength & protection',
    stoneMeanTurquoise: 'Good fortune & communication',
    nextEngrave: 'Next — Engrave',
    customEngraveQ: 'Add your engraving',
    engravingText: 'Text to engrave',
    engravingFeeLabel: '+{fee} kr',
    engravingInputPlaceholder: 'A name, initials, or date…',
    engravingHint: 'Max 16 characters · hand-engraved · optional — skip to continue',
    howItsDone: 'How it\'s done',
    howItsDoneText: 'Each letter is cut by hand using a traditional engraving tool — not laser-etched. The depth and texture give every piece a mark that\'s completely its own.',
    nextContact: 'Next — Contact',
    customContactQ: 'Almost done',
    customContactDesc: 'Leave your details and we\'ll be in touch to confirm your piece before we start crafting.',
    fullNamePlaceholder: 'Full name',
    phonePlaceholder: 'Phone (optional)',
    notesPlaceholder: 'Any extra details — who it\'s for, a special date, a photo reference…',
    sendDesignRequest: 'Send my design request',
    requestReceived: 'Request received',
    requestThankYouP1: 'Thank you,',
    requestThankYouFallback: 'there',
    requestThankYouP2: '. We\'ll reach out within 48 hours to begin crafting your piece together.',
    backToSiteBtn: 'Back to site',
    customDemoNote: 'Demo only — form is not yet wired to an email/backend.',
    yourDesign: 'Your design',
    materialLabel: 'Material',
    materialValue: 'Recycled Sterling Silver · 925',
    stoneLabel: 'Stone',
    engravingLabel: 'Engraving',
    estimatedTotal: 'Estimated total',
    summaryNote: 'Final price confirmed at consultation · handmade to order · 5–7 days',
    innerBandEngrave: 'Inner band engraving',
    outerFaceEngrave: 'Outer face engraving',
    yourTextPlaceholder: 'YOUR TEXT',

    // ── Loyalty / Account page ────────────────────────────────────────────────
    yourAccount: 'Your Account', theLianeCircle: 'The LIANELA Circle',
    myOrders: 'My Orders', history: 'History', returns: 'Returns', benefits: 'Circle Benefits',
    silverMember: 'Silver Member',
    memberSpend: '5 730 kr lifetime spend · Gold at 6 000 kr',
    activeOrders: 'Active orders',
    trackCurrentShipments: 'Track your current shipments in real time.',
    noActiveOrders: 'No active orders right now.',
    orderHistory: 'Order history',
    allPastPurchases: 'All your past LIANELA purchases.',
    returnsRefunds: 'Returns & refunds',
    returnsDesc: 'Items you\'ve returned and the status of your refunds.',
    noReturns: 'No returns on record.',
    returnsNote: 'To start a return, email us at returns@lianela.com within 14 days of delivery. Items must be unworn and in original packaging.',
    statusProcessing: 'Processing', statusShipped: 'Shipped',
    statusOutForDelivery: 'Out for delivery', statusDelivered: 'Delivered',
    statusRefunded: 'Refunded', statusReturnRequested: 'Return requested',
    trackOrder: 'Track order', hideTracking: 'Hide tracking',
    estimatedDelivery: 'Estimated delivery:',
    orderId: 'Order', deliveredOn: 'Delivered',
    returnedFrom: 'from order', returnRequested: 'Requested',
    returnReason: 'Reason:', refundProcessed: '✓ Refund processed on',
    membershipLevels: 'Membership levels',
    threeTiers: 'Three tiers. Lifetime rewards.',
    joinFree: 'Join free',
    createCircleAccount: 'Create your Circle account',
    takes30seconds: 'Takes 30 seconds. No purchase required.',
    fullName: 'Full name', yourName: 'Your name',
    emailAddress: 'Email address',
    birthday: 'Birthday',
    optional: 'optional', birthdayGiftNote: 'for your birthday gift',
    agreeText: 'I agree to receive member communications from LIANELA. You can unsubscribe at any time.',
    joinCircleBtn: 'Join the Circle — it\'s free',
    neverShareData: 'We never share your data.',
    welcomeToCircle: 'Welcome to the Circle',
    startShopping: 'Start shopping',
    mostPopular: 'Most popular',
    tierSilverName: 'Silver', tierSilverFrom: 'From first purchase',
    tierGoldName: 'Gold', tierGoldFrom: 'After 2 000 kr spent',
    tierDiamondName: 'Diamond', tierDiamondFrom: 'After 6 000 kr spent',
    perk5off: '5% off every order', perkEarlyAccess: 'Early access to new drops', perkBirthday: 'Birthday gift',
    perk10off: '10% off every order', perkPriorityCustom: 'Priority custom orders',
    perkSeasonalGifts: 'Seasonal gifts', perkFreeEngraving: 'Free engraving',
    perk15off: '15% off every order', perkStylist: 'Dedicated stylist',
    perkExclusive: 'Exclusive pieces first', perkFreeShipping: 'Free shipping always',
    perkCleaning: 'Annual complimentary cleaning',
    orderStepConfirmed: 'Order confirmed', orderStepEngraving: 'Engraving & prep',
    orderStepShipped: 'Shipped', orderStepOutForDelivery: 'Out for delivery',
    orderStepDelivered: 'Delivered',

    // ── Sets page ─────────────────────────────────────────────────────────────
    addSetToCart: 'Add set to cart',

    // ── Footer ────────────────────────────────────────────────────────────────
    footerTagline: 'Fine jewelry, quietly made. Stockholm · est. 2026.',
    shopCol: 'Shop', companyCol: 'Company', newsletterCol: 'Newsletter',
    newsletterNote: 'Early access to new drops.',
    emailPlaceholder: 'Email', joinBtn: 'Join',
    aboutLiane: 'About LIANELA', loyaltyCircle: 'Loyalty Circle',
    silverAndStone: 'Silver & Stone', matchingSets: 'Matching Sets',
    armenianHeritage: 'Our Heritage', customOrders: 'Custom Orders',
    rights: '© 2026 LIANELA. All rights reserved.',
    privacy: 'Privacy · Terms · Cookies',
  },

  sv: {
    // ── Utility bar ───────────────────────────────────────────────────────────
    announce: 'Kostnadsfri gravyr · Fri frakt över 1 500 kr · Tillverkad i Stockholm',

    // ── Nav ───────────────────────────────────────────────────────────────────
    women: 'Dam', men: 'Herr', silverStone: 'Silver & Sten',
    sets: 'Set', heritage: 'Arv', collection: 'Kollektion',
    shopHer: 'Shoppa dam', shopHim: 'Shoppa herr',
    necklaces: 'Halsband', earrings: 'Örhängen', rings: 'Ringar', bracelets: 'Armband',
    signetRings: 'Signetringar', chains: 'Kedjor', cufflinks: 'Manschettknappar', viewAll: 'Visa alla →',

    // ── Home ──────────────────────────────────────────────────────────────────
    heroEyebrow: 'Línea-kollektionen', heroH1a: 'I full', heroH1b: 'blom',
    shopCollection: 'Shoppa kollektionen', ourStory: 'Vår berättelse',
    findYourPiece: 'Hitta ditt smycke', shopByCategory: 'Shoppa efter kategori',
    newArrivals: 'Nyheter', featuredPieces: 'Utvalda smycken',
    viewAll2: 'Visa alla', addToCart: 'Lägg i varukorg',
    marquee: 'Återvunnet guld ✦ Tillverkat i Stockholm ✦ Gammalt svenskt hantverk ✦ Livstidsreparation',
    forHer: 'För henne', forHim: 'För honom', forAll: 'För alla',
    newIn: 'Nyhet', lowStock: 'Få kvar',

    // ── Shop ──────────────────────────────────────────────────────────────────
    all: 'Alla',
    silverStoneEyebrow: 'Natursten, handfäst i sterlingsilver',
    shopEmpty: 'Inga smycken matchar detta filter ännu.',

    // ── Cart ──────────────────────────────────────────────────────────────────
    yourCart: 'Din varukorg', cartEmpty: 'Din väska är tom',
    cartEmptySub: 'Dina smycken visas här.',
    subtotal: 'Delsumma', toCheckout: 'Till kassan',
    freeShippingNote: 'Fri frakt över 1 500 kr',
    continueShopping: 'Fortsätt shoppa',

    // ── Product page ──────────────────────────────────────────────────────────
    addToCartBtn: 'Lägg i varukorg',
    back: '← Tillbaka',
    personalisableFlag: '✦ Detta smycke kan personaliseras',
    metalLabel: 'Metall',
    metalGold: 'Guld', metalWhiteGold: 'Vitt guld', metalSilver: 'Silver',
    accordionDetails: 'Detaljer & material',
    accordionSizing: 'Storlek & passform',
    accordionShipping: 'Frakt & returer',
    persEyebrow: 'Gjort för dig',
    persH2: 'Designa ditt eget',
    persIntro: 'Välj dina initialer, symbol, sten och metall. Vi graverar varje smycke för hand innan det skickas.',

    // ── Personalisation panel ─────────────────────────────────────────────────
    persPreviewNote: 'Live-förhandsgranskning · inte i skala',
    persHeadline: 'Personalisera detta smycke',
    persInitialsLabel: 'Graverade initialer',
    persInitialsPlaceholder: 't.ex. L · LA · LIA',
    persInitialsHint: '1–3 bokstäver, avgränsade med · vid behov',
    persSymbolLabel: 'Graverad symbol',
    persSymbol1: 'Solkors', persSymbol2: 'Evighetsknop', persSymbol3: 'Älgblomma',
    persMetal: 'Metall',
    persMetalSilver: 'Sterlingsilver', persMetalGold: 'Massivt guld',
    persStoneLabel: 'Stenaccent', persStoneNote: '— välj efter betydelse',
    persStoneNone: 'Ingen sten', persStoneGarnet: 'Granat', persStoneMoonstone: 'Månsten',
    persStoneAmethyst: 'Ametist', persStoneOnyx: 'Svart onyx',
    persChainLabel: 'Kedjelängd',
    persAddInitials: 'LÄGG TILL INITIALER',
    persDisclaimer: 'Varje smycke handavslutas på beställning · räkna med 5–7 dagar',

    // ── Checkout ──────────────────────────────────────────────────────────────
    placeOrder: 'Lägg beställning',
    orderSummary: 'Orderöversikt',
    shipping: 'Frakt', free: 'Gratis', total: 'Totalt',
    firstName: 'Förnamn', lastName: 'Efternamn',
    address: 'Adress', city: 'Stad', postalCode: 'Postnummer', country: 'Land',
    email: 'E-post', phone: 'Telefon',
    cardNumber: 'Kortnummer', expiry: 'Giltig till', cvc: 'CVC',

    // ── About page ────────────────────────────────────────────────────────────
    aboutEyebrow: 'Sedan 2026',
    aboutH1: 'Gammalt hantverk. Nya händer.',
    aboutQuote: '"Svenska silversmeder graverade en gång motiv som bar mening i generationer. Jag ville föra det vidare — inte som nostalgi, utan som något du faktiskt bär."',
    aboutP1: 'Grundat av Liana i Stockholm återupplivar LIANELA förmodern svensk metallsmide — inspirerat av nordisk knotwork, folkliga motiv och gamla lödningstekniker som i stort sett försvann med massproduktionen. Varje smycke tillverkas i små serier av återvunnet massivt guld och ansvarsfullt utvunna stenar.',
    aboutP2: 'Vi tror att smycken ska levas i — bäras varje dag, föras vidare, repareras snarare än bytas ut. Varje LIANELA-beställning bär ett livslångt hantverkslöfte.',
    aboutStat1: 'Återvunnet guld', aboutStat2: 'Reparationsgaranti', aboutStat3: 'Skickas från Stockholm',
    exploreCollection: 'Utforska kollektionen',

    // ── Heritage page ─────────────────────────────────────────────────────────
    heritageEyebrow: 'Svenskt hantverksarv',
    heritageH1: 'Symboler burna i silver',
    heritageP: 'Varje motiv vi graverar går tillbaka till forntida svensk metallsmide — mönster skurna för hand i järn, ben och silver i mer än tusen år. Vi för dem vidare i sterlingsilver, valda för vad de betyder, inte bara hur de ser ut.',
    heritageCtaP: 'Vill du ha en symbol som inte visas här, anpassad i storlek eller graverad för någon speciell?',
    heritageCtaBtn: 'Beställ ett specialsmycke',

    // ── Custom order page ─────────────────────────────────────────────────────
    customTitle: 'Specialbeställning',
    customEyebrow: 'Bara för dig',
    customH1: 'Designa ditt eget smycke',
    customHeroDesc: 'Välj ditt smycke och din sten. Lägg till ett namn, en initial, ett datum. Vi graverar och handavslutar varje specialbeställning i återvunnet sterlingsilver.',
    customBegin: 'Börja',
    stepPiece: 'Smycke', stepStone: 'Sten', stepEngrave: 'Gravering', stepContact: 'Kontakt',
    customPieceQ: 'Vad vill du skapa?',
    customPieceDesc: 'Ring eller armband — vi skapar resten utifrån ditt val.',
    pieceRing: 'Ring', pieceRingSub: 'Band / signetring',
    pieceBracelet: 'Armband', pieceBraceletSub: 'Cuff / bangle',
    pieceEngRing: 'Graverat på insidan av bandet — ett hemligt meddelande som bara du känner till.',
    pieceEngBracelet: 'Graverat på utsidan — synligt, personligt och permanent.',
    backToSite: '← Tillbaka till sajten',
    nextStone: 'Nästa — Sten',
    customStoneQ: 'Välj din sten',
    customStoneDesc: 'Varje sten bär sin egen betydelse. Alla smycken tillverkas i återvunnet sterlingsilver.',
    silverBadge: 'Återvunnet sterlingsilver · 925',
    silverBadgeNote: 'etiskt utvunnet · handpolerat · hallstämplat',
    stoneNone: 'Ingen sten', stoneGarnet: 'Granat', stoneMoonstone: 'Månsten',
    stoneAmethyst: 'Ametist', stoneOnyx: 'Svart onyx', stoneTurquoise: 'Turkos',
    stoneMeanGarnet: 'Mod & vitalitet', stoneMeanMoonstone: 'Balans & nya början',
    stoneMeanAmethyst: 'Frid & intuition', stoneMeanOnyx: 'Styrka & skydd',
    stoneMeanTurquoise: 'Lycka & kommunikation',
    nextEngrave: 'Nästa — Gravering',
    customEngraveQ: 'Lägg till din gravering',
    engravingText: 'Text att gravera',
    engravingFeeLabel: '+{fee} kr',
    engravingInputPlaceholder: 'Ett namn, initialer eller datum…',
    engravingHint: 'Max 16 tecken · handgraverat · valfritt — hoppa över för att fortsätta',
    howItsDone: 'Hur det går till',
    howItsDoneText: 'Varje bokstav skärs för hand med ett traditionellt graveringsinstrument — inte laseretsning. Djupet och texturen ger varje smycke ett märke som är helt unikt.',
    nextContact: 'Nästa — Kontakt',
    customContactQ: 'Nästan klart',
    customContactDesc: 'Lämna dina uppgifter så hör vi av oss för att bekräfta ditt smycke innan vi börjar.',
    fullNamePlaceholder: 'Fullständigt namn',
    phonePlaceholder: 'Telefon (valfritt)',
    notesPlaceholder: 'Ytterligare detaljer — vem det är till, ett speciellt datum, en bildreferens…',
    sendDesignRequest: 'Skicka min designförfrågan',
    requestReceived: 'Förfrågan mottagen',
    requestThankYouP1: 'Tack,',
    requestThankYouFallback: 'du',
    requestThankYouP2: '. Vi hör av oss inom 48 timmar för att börja skapa ditt smycke tillsammans.',
    backToSiteBtn: 'Tillbaka till sajten',
    customDemoNote: 'Demo — formuläret är ännu inte kopplat till e-post/backend.',
    yourDesign: 'Din design',
    materialLabel: 'Material',
    materialValue: 'Återvunnet sterlingsilver · 925',
    stoneLabel: 'Sten',
    engravingLabel: 'Gravering',
    estimatedTotal: 'Uppskattad totalsumma',
    summaryNote: 'Slutpriset bekräftas vid konsultation · handgjort på beställning · 5–7 dagar',
    innerBandEngrave: 'Gravering på insidan av bandet',
    outerFaceEngrave: 'Gravering på utsidan',
    yourTextPlaceholder: 'DIN TEXT',

    // ── Loyalty / Account page ────────────────────────────────────────────────
    yourAccount: 'Ditt konto', theLianeCircle: 'LIANELA-cirkeln',
    myOrders: 'Mina beställningar', history: 'Historik', returns: 'Returer', benefits: 'Förmåner',
    silverMember: 'Silvermedlem',
    memberSpend: '5 730 kr livstidsköp · Guld vid 6 000 kr',
    activeOrders: 'Aktiva beställningar',
    trackCurrentShipments: 'Spåra dina aktuella leveranser i realtid.',
    noActiveOrders: 'Inga aktiva beställningar just nu.',
    orderHistory: 'Beställningshistorik',
    allPastPurchases: 'Alla dina tidigare LIANELA-köp.',
    returnsRefunds: 'Returer & återbetalningar',
    returnsDesc: 'Artiklar du har returnerat och status på dina återbetalningar.',
    noReturns: 'Inga registrerade returer.',
    returnsNote: 'För att starta en retur, maila oss på returns@lianela.com inom 14 dagar efter leverans. Artiklarna måste vara oanvända och i originalförpackning.',
    statusProcessing: 'Behandlas', statusShipped: 'Skickad',
    statusOutForDelivery: 'Under leverans', statusDelivered: 'Levererad',
    statusRefunded: 'Återbetald', statusReturnRequested: 'Retur begärd',
    trackOrder: 'Spåra beställning', hideTracking: 'Dölj spårning',
    estimatedDelivery: 'Beräknad leverans:',
    orderId: 'Beställning', deliveredOn: 'Levererad',
    returnedFrom: 'från beställning', returnRequested: 'Begärd',
    returnReason: 'Anledning:', refundProcessed: '✓ Återbetalning behandlad',
    membershipLevels: 'Medlemsnivåer',
    threeTiers: 'Tre nivåer. Livstidsförmåner.',
    joinFree: 'Gå med gratis',
    createCircleAccount: 'Skapa ditt Circle-konto',
    takes30seconds: 'Tar 30 sekunder. Inget köp krävs.',
    fullName: 'Fullständigt namn', yourName: 'Ditt namn',
    emailAddress: 'E-postadress',
    birthday: 'Födelsedag',
    optional: 'valfritt', birthdayGiftNote: 'för din födelsedagspresent',
    agreeText: 'Jag godkänner att ta emot kommunikation från LIANELA. Du kan avregistrera dig när som helst.',
    joinCircleBtn: 'Gå med i Circle — kostnadsfritt',
    neverShareData: 'Vi delar aldrig dina uppgifter.',
    welcomeToCircle: 'Välkommen till Circle',
    startShopping: 'Börja shoppa',
    mostPopular: 'Mest populär',
    tierSilverName: 'Silver', tierSilverFrom: 'Från första köpet',
    tierGoldName: 'Guld', tierGoldFrom: 'Efter 2 000 kr spenderade',
    tierDiamondName: 'Diamant', tierDiamondFrom: 'Efter 6 000 kr spenderade',
    perk5off: '5% rabatt på varje beställning', perkEarlyAccess: 'Tidig tillgång till nyheter', perkBirthday: 'Födelsedagspresent',
    perk10off: '10% rabatt på varje beställning', perkPriorityCustom: 'Prioriterade specialbeställningar',
    perkSeasonalGifts: 'Säsongsgåvor', perkFreeEngraving: 'Gratis gravering',
    perk15off: '15% rabatt på varje beställning', perkStylist: 'Dedikerad stilist',
    perkExclusive: 'Exklusiva smycken först', perkFreeShipping: 'Alltid fri frakt',
    perkCleaning: 'Årlig kostnadsfri rengöring',
    orderStepConfirmed: 'Beställning bekräftad', orderStepEngraving: 'Gravering & förberedelse',
    orderStepShipped: 'Skickad', orderStepOutForDelivery: 'Under leverans',
    orderStepDelivered: 'Levererad',

    // ── Sets page ─────────────────────────────────────────────────────────────
    addSetToCart: 'Lägg set i varukorg',

    // ── Footer ────────────────────────────────────────────────────────────────
    footerTagline: 'Fina smycken, stilla skapade. Stockholm · est. 2026.',
    shopCol: 'Butik', companyCol: 'Företag', newsletterCol: 'Nyhetsbrev',
    newsletterNote: 'Tidig tillgång till nya kollektioner.',
    emailPlaceholder: 'E-post', joinBtn: 'Gå med',
    aboutLiane: 'Om LIANELA', loyaltyCircle: 'Loyalty Circle',
    silverAndStone: 'Silver & Sten', matchingSets: 'Matchande set',
    armenianHeritage: 'Vårt arv', customOrders: 'Specialbeställningar',
    rights: '© 2026 LIANELA. Alla rättigheter förbehållna.',
    privacy: 'Integritet · Villkor · Cookies',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = (key) => T[lang][key] ?? T.en[key] ?? key
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
